export type Project = {
  slug: string;
  title: string;
  year: string;
  image: string;
  detailImages: string[];
  intro: string;
  overview: string;
  overviewBody: string;
  solution: string;
};

const defaultIntro = "Interior design is the thoughtful harmony of vision and precision, reimagining spaces to foster wellness, comfort, and timeless style through curated aesthetics and purposeful function.";
const defaultOverview = "Interior architecture is the refined blend of design, science, and spatial planning—shaping environments with creativity and precision. It tells stories, captures culture, and defines the character of every space.";
const defaultBody = "Every project is developed around the people who will use it. Thoughtful planning, material selection, lighting, and craftsmanship come together to create an environment that feels personal, functional, and enduring.";
const defaultSolution = "Our designers bring vision, technical insight, and careful problem solving to every detail. Sustainability, well-being, and lasting quality guide the process from the first drawing through final execution.";

export const projects: Project[] = [
  { slug: "urban-nest", title: "Urban Nest", year: "2019", image: "/images/urban-nest.jpg", detailImages: ["/images/urban-nest-overview-1.jpeg", "/images/urban-nest-overview-2.jpeg", "/images/urban-nest-solution-1.png", "/images/urban-nest-solution-2.png"], intro: defaultIntro, overview: "Interior architecture is the refined blend of design, science, and spatial engineering—shaping our living environments with creativity and precision. It’s more than arranging space; it tells stories, captures cultures, and defines the character of each era.", overviewBody: "A premier address in the heart of Patna, our 46-story concept reimagines commercial interiors with a refined blend of structure and elegance. Designed with a dynamic silhouette, the space features a curved façade and seamlessly integrates restored heritage elements, reflecting Urban Nest’s dedication to timeless yet modern design.", solution: "Interior designers are the visionaries, storytellers, and problem solvers of the built environment. Their role goes beyond beauty and function—it shapes how we live, feel, and connect. With sustainability at the core, today’s designers create spaces that breathe with nature and nurture well-being." },
  { slug: "modern-residence", title: "Modern Residence", year: "2024", image: "/images/modern-residence.png", detailImages: ["/images/modern-residence-overview-1.png", "/images/modern-residence-overview-2.png", "/images/modern-residence-solution-1.png", "/images/modern-residence-solution-2.png"], intro: defaultIntro, overview: defaultOverview, overviewBody: defaultBody, solution: defaultSolution },
  { slug: "the-white-haven", title: "The White Haven", year: "2021", image: "/images/white-haven.png", detailImages: ["/images/white-haven-overview-1.png", "/images/white-detail-1.jpeg", "/images/white-detail-2.png", "/images/white-detail-3.png"], intro: "Interior design is the thoughtful fusion of artistic intuition and scientific planning, enhancing indoor—and at times, outdoor—spaces to create a more comforting, visually enriching, and health-conscious environment tailored for everyday living.", overview: "Interior architecture is the elegant union of art, science, and spatial design—shaping living environments with purpose and grace. It transcends structure, becoming a language that narrates lifestyles, reflects personal identity, and defines timeless domestic character.", overviewBody: "Interior architecture is the seamless blend of art, science, and refined spatial planning—transforming houses into deeply personal sanctuaries. It’s more than creating structures; it’s about designing spaces that reflect identity, evoke emotion, honor culture, and stand timeless in form and function.", solution: "Interior designers are the dreamers, storytellers, and problem solvers of the spaces we call home. Their vision goes far beyond beauty—it shapes how we live, rest, and connect. At White Haven, the focus is on wellness, warmth, and harmony with nature." },
  { slug: "mithusa-unisex-salon", title: "Mithusa Unisex Salon", year: "2025", image: "/images/salon.jpeg", detailImages: ["/images/mithusa-overview-1.jpeg", "/images/mithusa-overview-2.jpeg", "/images/mithusa-solution-1.jpeg", "/images/mithusa-solution-2.jpeg"], intro: defaultIntro, overview: defaultOverview, overviewBody: defaultBody, solution: defaultSolution },
  { slug: "elevate-gym-space", title: "Elevate Gym Space", year: "2020", image: "/images/elevate-gym.avif", detailImages: ["/images/elevate-gym-overview-1.jpg", "/images/elevate-gym-overview-2.jpg", "/images/elevate-gym-solution-1.jpg", "/images/elevate-gym-solution-2.jpg"], intro: "Interior design is the blend of artistic and scientific principles used in Elevate Gym to transform functional workout areas into energizing, health-forward spaces that motivate movement while maintaining style, balance, and well-being.", overview: "Interior architecture is the refined blend of design, science, and spatial planning, shaping wellness-driven environments with intention and creativity. At Elevate Gym, every detail tells a story, reflects modern fitness culture, and redefines functional luxury.", overviewBody: "Elevate Gym is a multi-level wellness destination designed to stand out with a sleek, contemporary identity. The team optimized the layout and materials—from fluid spatial planning to custom cladding—creating an inspiring space where function and form meet in motion.", solution: "Designers are the visionaries, problem solvers, and storytellers behind transformative fitness spaces. At Elevate Gym, design moves beyond aesthetics and utility—it shapes how we move, feel, and thrive. With wellness and sustainability at the core, the interiors elevate everyday routines." },
  { slug: "modern-minimalist-house", title: "Modern Minimalist House", year: "2023", image: "/images/minimalist.jpeg", detailImages: ["/images/minimalist-overview-1.jpeg", "/images/minimalist-overview-2.png", "/images/minimalist-solution-1.png", "/images/minimalist-solution-2.png"], intro: defaultIntro, overview: defaultOverview, overviewBody: defaultBody, solution: defaultSolution },
  { slug: "modern-restaurant", title: "Modern Restaurant", year: "2022", image: "/images/restaurant.png", detailImages: ["/images/restaurant-overview-1.png", "/images/restaurant-overview-2.png", "/images/restaurant-solution-1.png", "/images/restaurant-solution-2.png"], intro: defaultIntro, overview: defaultOverview, overviewBody: defaultBody, solution: defaultSolution },
  { slug: "rustic-steel-house", title: "Rustic Steel House", year: "2021", image: "/images/rustic.jpeg", detailImages: ["/images/rustic-overview-1.jpeg", "/images/rustic-overview-2.jpeg", "/images/rustic-solution-1.jpeg", "/images/rustic-solution-2.jpeg"], intro: defaultIntro, overview: defaultOverview, overviewBody: defaultBody, solution: defaultSolution },
  { slug: "dental-clinic", title: "Dental Clinic", year: "2020", image: "/images/dental.jpg", detailImages: ["/images/dental-overview-1.png", "/images/dental-overview-2.png", "/images/dental-solution-1.jpg", "/images/dental-solution-2.png"], intro: defaultIntro, overview: defaultOverview, overviewBody: defaultBody, solution: defaultSolution },
];

export const getProject = (slug: string) => projects.find((project) => project.slug === slug);